version: '3'

services:
  app:
    build:
      context: .
      # target: development
      target: production
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_MAX_RETRIES=${DB_MAX_RETRIES}
      - DB_RETRY_INTERVAL=${DB_RETRY_INTERVAL}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - ENCRYPTION_IV_LENGTH=${ENCRYPTION_IV_LENGTH}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRY=${JWT_EXPIRY}
      - PAGINATION_DEFAULT_LIMIT=${PAGINATION_DEFAULT_LIMIT}
      - PAGINATION_DEFAULT_PAGE=${PAGINATION_DEFAULT_PAGE}
    volumes:
      # - ./src:/app/src
      - ./logs:/app/logs
      # - ./.env:/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    volumes:
      - mongo-data:/data/db
    ports:
      - "$DB_PORT:27017"

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=${EXPRESS_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${EXPRESS_PASSWORD} 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:${DB_PORT}/
    depends_on:
      - mongo

volumes:
  mongo-data:
